# Perfil activo por defecto
spring.profiles.active=dev

# Configuracion del servidor
server.port=8080

# Configuracion JPA comun
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=minijira-secret-key-must-be-at-least-256-bits-long-for-hs256-algorithm
jwt.expiration=86400000
